apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-demo
  labels:
    app: api-demo
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: api-demo-https-secret
      hosts:
        - api-demo.techtalk.cna-demo.ga
  rules:
    - host: api-demo.techtalk.cna-demo.ga
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: api-demo
                port: 
                    name: http
