apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elastic-privileged-psp
  namespace: elastic
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: elastic
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logging
  namespace: elastic
spec:
  version: 7.12.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logging
  namespace: elastic
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: logging
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logging-es
  namespace: elastic
  labels:
    app: logging-es
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: logging-es-https-secret
      hosts:
        - logs.techtalk.cna-demo.ga
  rules:
    - host: logs.techtalk.cna-demo.ga
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: logging-es-http
                port: 
                    name: http
---
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logging-kb
  namespace: elastic
  labels:
    app: logging-kb
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: logging-kb-https-secret
      hosts:
        - log-ui.techtalk.cna-demo.ga
  rules:
    - host: log-ui.techtalk.cna-demo.ga
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: logging-kb-http
                port: 
                    name: http
